### ISSUE TITLE
Selected MII instead of RMII

### ISSUE THREAD

**Issue by Mobivlad** [RomanYAC/Embedded_Lab3#1]
KSZ8021RNL connected to STM by RMII

![image](https://user-images.githubusercontent.com/17147322/78144514-5d44c500-7438-11ea-9619-a43ff9a4cf4c.png)

https://github.com/RomanYAC/Embedded_Lab3/blob/7dafd633b25219265afda9e16d89c4b88db58884/src/TCP_Client/inc/main.h#L85-L93

**Comment by RomanYAC** [comment]
Thank you for attention, this issue is resolved
