### ISSUE TITLE
Incorrect PHY_ADR

### ISSUE THREAD

**Issue by Mobivlad** [RomanYAC/Embedded_Lab3#3]
https://github.com/RomanYAC/Embedded_Lab3/blob/2c0bcd991598fa78a7fad80c115417a0a89d1a5d/src/TCP_Client/inc/stm32f4x7_eth_bsp.h#L53

![image](https://user-images.githubusercontent.com/17147322/78164537-8d995d00-7452-11ea-8454-1442a15ef266.png)

**Comment by RomanYAC** [comment]
If I understand You, it should be

#define DP83848_PHY_ADDRESS       ((uint16_t) 0x3h) ,

Right?

**Comment by Mobivlad** [comment]
@RomanYAC I am not sure, It depends on what level is in the pin.
![image](https://user-images.githubusercontent.com/17147322/78176154-baef0680-7464-11ea-8d99-a060d1acd712.png)
The pin isn't connected to VCC or to GND, so PHY_AD must be 0x00, the default value.
But I don't really know.

**Comment by RomanYAC** [comment]
Gotcha, thank you for explanaition.

**Comment by RomanYAC** [comment]
Resolved in https://github.com/RomanYAC/Embedded_Lab3/pull/4
